---
title: A Final 2020 Summer Book Review - The Stand
date: 2020-09-17
---
Be Warned: Spoilers Ahead!

I did it. I finished *The Stand*. PHEW.

I’ve had Steven King’s Bible-sized novel on my to-read list for a very long time, and this summer’s Covid-induced freeze on pretty much everything finally gave me the time to really sit down and dig into it. I should start this post by saying that, yes, I absolutely loved it. Yes, it absolutely deserves all of the acclaim and prestige and accolades its received since it was first published in 1978. Yes, it is a huuuggggeeee book that took me most of the summer to read, and I feel a mix of accomplishment and relief that I can check it off my list, but also a bit of nostalgia for when I was really deep in the weeds, and the plot started to ramp up for the absolutely buck-wild final third of the novel.

I have a few specific points of interest I want to reflect on a bit as I try to process what King was trying to get at with *The Stand*, but I want to preface everything by just noting that, as a holistic package, the book is an absolute blast. Totally worth the time investment; I’d recommend it to pretty much anyone. 

To try to summarize the plot of this behemoth of a novel would be farcical, but just to set some context around this post: the book is partially about a man-made superflu epidemic which decimates the overwhelming majority of the population of the United States (it is *heavily* implied that the rest of the world meets the same fate, but King’s tale focuses on the experiences of American citizens). The first half of the book is a dystopian narrative which follows the cast of main characters as they reckon with the societal collapse brought on by the supervirus. 

Although really, collapse isn’t totally the correct description - its more that society simply disappears, almost overnight, as the overwhelming majority of the population succumbs to the epidemic. 

The second half of the book becomes significantly more theological, as the survivors are drawn towards two camps - one of which is run by Mother Abagail, who serves as the mouthpiece for God, and the others are drawn towards a man named Randall Flagg, who represents Satan, or perhaps simply the antithesis of God, whatever that might be in King’s multiverse. The subsequent plot becomes significantly more mythological, but perhaps even more apocalyptic than the onslaught of the supervirus, as the two camps face against each other and struggle to determine which moral framework will attain dominance in the new world.  

Like I said - an extremely difficult book to summarize. 

It was especially cutting (I think that’s the right word? I’m not totally sure what I’m trying to express here) reading this book while experiencing the real-life epidemic of 2020. King’s description of how the world responds to the superflu was honestly pretty prescient. While King’s superflu is essentially incurable, the rapidity of its spread is exacerbated by a lack of a common source of truth about the virus and its properties. The virus originates from a secret US lab, but the government plays cover-up, refusing to take blame for the virus and instead it broadcasts misinformation in order to protect itself from accusation (which, of course, is a moot point entirely as the government almost immediately collapses). As I was reading *The Stand*, I found myself reflecting on how the  “post-truth” environment of the late twenty-teens has, unfortunately, created a similar social climate, where the efficacy of masks is somehow under scrutiny as a Marxist plot, and the United States is more interested in pointing fingers than it is in acknowledging that we have pretty fundamentally failed in our response to COVID since January or February. 

Of course, this immediately causes me to wonder what King was tapping into when he wrote the novel that allows his claims about humanity to have such prescience three decades later. I think, across King’s work, he is extremely, extremely good at thinking through the systemic and long-term effects of human pride and our innate tendency to admit fault when it has been exposed to us. Later in the book, as Flagg continues to build his “evil” empire in Las Vegas, many of his constituents realize cognitively that they are on the wrong side of the moral battle that is taking place. It is their inability to “turn back,” or recant their position, that drives them towards their inevitable doom. Human pride is the primary vehicle which Flagg (I.e. anti-God, or Satan, or whatever “Evil” is) uses to build his vision of civilization from the ashes of the old. 

This is the same flaw that drives Pennywise’s control of Derry in *It*, and to a lesser extent, pride drives The Gunslinger in *The Dark Tower* on his quest as he contends against the Dark Man (who, interestingly, is the same entity as Flagg in the Kingiverse). King is the best thinker on the ramifications of human pride and its corrupting influence that I’ve read. He consistently follows pride to its systemically horrifying conclusions across all of his books - really, its what makes his stories so creepy to me. They are far, far too similar to real life. 
