---
title: A 2020 Summer Book Report (If Reports Were Lists)
date: 2020-08-03
---
Again, as I'm figuring out how to do this blog thing, much credit goes to my friend Robbie's [post](https://robertsapunarich.com/blog/2020/08/02/favorite-reads-first-half-2020/) on what he's been reading in the first half of the year. This seems like as good a time as any to go back through my Goodreads list and try to remember how I've been spending quarantine.

#### *The Fifth Season*  - N.K. Jemisin
 Very cool mix of pretty classic fantasy with post-apocalyptic dystopian fiction which weaves in really insightful commentary on race/class. This book seems to often subvert the white-European-male fantasy tropes that everyone loves to point out but noone actually deals with in any meaningful way. 
    
#### *Bury My Heart at Wounded Knee: An Indian History of the American West* - Dee Brown
I mentioned this book and *Haunting of Hill House* in my [last post](https://www.zackverham.com/7-16-2020/) - this book is still sitting with me pretty deep. 
#### *The Haunting of HIll House* - Shirley Jackson
#### *Black Theology and Black Power* - James Cone
#### *Uzumaki* - Junji Ito
My second foray into Manga (after *Akira*). I've read Ito's internet-(in)famous *Enigma of Amigara Fault*, so I had a general idea of what I was getting into, but I was not expecting this book to be as spooky as it was by a long-shot. Very Lovecraftian - I don't think this story would work outside of the visual illustrations it provides (they're buck-wild).
#### *Blood Meridian: Or the Evening Redness in the West* - Cormac McCarthy
Judge Holden is terrifying. Initially I was pretty revolted by this book, but I saw that Yale has some [open lectures](https://oyc.yale.edu/english/engl-291/lecture-17) on *Blood Meridian* which helped me make sense of the fact that revulsion is kind of the point. It was interesting pairing this book, which functions as a pretty extreme example of an [anti-western](https://en.wikipedia.org/wiki/Revisionist_Western), with *Bury My Heart at Wounded Knee*. I think there is at least some overlap between the two in trying to break down and re-think the mythological glory of the American west.
#### *The Scapegoat* - Rene Girard
#### *The Anarchy: The East India Company, Corporate Violence, and the Pillage of an Empire* - William Dalrymple
#### *The Dangers of Christian Practice: On Wayward Gifts, Characteristic Damage, and Sin* - Lauren F. Winner
This book proposes the (I think correct) thesis that Christian practices and sacraments are susceptible to sin in ways that are *inherent* to those practices. The example that felt most pointed to me were the anti-Semitic [host desecration](https://en.wikipedia.org/wiki/Host_desecration#Medieval_accusations_against_Jews) accusations which led to pogroms in medieval Europe. Winner argues that these massacres were at least partially driven by the particular form and structure of the Eucharist as it is practiced in Christian churches. Absolutely worth the read.

#### *The Stranger* - Albert Camus
Camus' [philosophy of the absurd ](https://en.wikipedia.org/wiki/Absurdism)feels especially relevant in the Covid hellscape - *The Stranger* helped to re-frame the more technical work Camus lays out in *The Myth of Sisyphus* as something which felt more immediately applicable and digestible. I read *Sisyphus* first, but I wish I had read them the other way around. 
#### *The Myth of Sisyphus* - Albert Camus
#### *Black Panther #1* - Ta-Nehisi Coates
#### *The Shock Doctrine: The Rise of Disaster Capitalism* - Naomi Klein
#### *Watchmen* - Alan Moore, Dave Gibbons, John Higgins
