---
title: "Writing"
---

## Mockingbird

- [The King in Purple: Cosmic Horror and the Cosmic Christ](https://mbird.com/2021/03/the-king-in-purple-cosmic-horror-and-the-cosmic-christ/)
- [Mental Health, OCD, and God](https://mbird.com/2020/12/mental-health-ocd-and-god/)
- [The Gospel According to Dune](https://mbird.com/2020/05/the-gospel-according-to-dune/)
- [The Absurdity of Death: A Lenten Reflection on Camus](https://mbird.com/2020/03/the-absurdity-of-death-a-lenten-reflection-on-camus/)
- [I'm a Vampire! I'm a Vampire! I'm a Vampire!](https://mbird.com/2019/05/im-a-vampire-im-a-vampire-im-a-vampire/)
- [Crime and Punishment and Adventure Time: A Kierkegaardian Reflection on Lowliness](https://mbird.com/2019/01/crime-and-punishment-and-adventure-time-a-kierkegaardian-reflection-on-lowliness/)
- [Thank God for Mr. Bubz](https://mbird.com/2018/12/thank-god-for-mr-bubz/)
- [To Dissolve the Line Between Man and Machine: Reflections on Cyberpunk and the Meatspace](https://mbird.com/2018/11/to-dissolve-the-line-between-man-and-machine-reflections-on-cyberpunk-and-the-meatspace/)
- [A Message of Hope for the Geeks: From Coheed and Cambria](https://mbird.com/2018/08/a-message-of-hope-for-the-geeks-from-coheed-and-cambria)
- [Meme Lore 101: Lecture 1 - Course Overview](https://mbird.com/2018/04/meme-lore-101-lecture-1-course-overview/)
- [Incomplete Math and the Paradox of Grace](https://mbird.com/2018/02/incomplete-math-and-the-paradox-of-grace/)
- [Gospel Moshing: Adventures at Metal Shows with a Spooky Friend](https://mbird.com/2017/10/gospel-moshing-adventures-at-metal-shows-with-a-spooky-friend/)
- [I Roll to Punch the Shark: The Strangely Familiar World of Dungeons and Dragons](https://mbird.com/2017/07/i-roll-to-punch-the-shark-the-strangely-familiar-world-of-dungeons-and-dragons/)
- [The Ultimate Apocalypse](https://mbird.com/2017/03/the-ultimate-apocalypse/)

## Miscellaneous

- [Utah. Published in "One for the Road: An Anthology of Roadtrip Writing" (2020-06-16).](https://www.amazon.com/dp/B08BF14HNN?ref_=pe_3052080_397514860)
- [The Invisibility of Online Slavery. Published in Intersect: The Stanford Journal of Science, Technology, and Society (2015-07-13)](https://ojs.stanford.edu/ojs/index.php/intersect/article/view/721)
