---
title: A Quick Fall Music Update
date: 2020-10-19
---

I just wanted to do a quick post to try to minimize the interval between publications here - I’m trying to collect some thoughts for a bigger, more long-form thing, but we’ll see what ends up happening with that. 

Fall has arrived in Appalachia - the leaves are changing colors, but I can’t really tell because, hey, colorblindness. 

Over the past little bit I’ve been getting *really* into Phoebe Bridgers and Julien Baker - two-thirds of the [boygenius](https://youtu.be/96wDhimQ6nw) supergroup trio. I was already jamming Bridgers’ album *Punisher*, but having the context of more of her discography has made the album a lot richer for me. This past weekend she demolished a set as part of the [Save Our Stages](https://www.saveourstages.com/) fundraiser, which is a response to the economic hardship being faced by local music venues during the pandemic. Definitely  [check this shit out](https://www.youtube.com/watch?v=InqXSsPI5eA). 

Julien has been a gem of a find. She’s the first Christian singer / songwriter I’ve encountered in a long time that I genuinely want to recommend to people without any modifiers or brackets around the [Christian] part. No cringey platitudes or garbage theology in these waters. She wrestles with faith, doubt, and her own mental well-being in a way that points toward the Gospel as something deeply personal and universal.  This [NPR Tiny Desk Concert](https://www.youtube.com/watch?v=tADWPTqR_4A) is wonderful. 

That’s really all I’ve got for now - go check out those concerts boiiiiiii
