---
title: A First Post
date: 2020-06-27
---

*Well, I honestly don't really know how to start this, so I'll just jump in with a brief opener post:*

Over the past couple of years, I've found myself coming to terms with the fact that current social media landscape is pretty busted. Other folks who are much smarter than me have laid out grand manifestos and treatises on the adverse effects of modern social platforms, but my thoughts are pretty simple - I just honestly have had no desire to post on them in a really, really long time. If I have anything worthwhile to say, I just contact my closer circle of friends directly, and reading through the constant toxicity and bickering of people I barely know on my timelines and news feeds was honestly just draining. It wasn't worth it to me - and that's pretty much as complex of an analysis as I care to think through. So I cashed out. I'm off Facebook and Instagram now, and I only have a Twitter to follow meme accounts.

Which brings me here - to this new "experiment" of sorts. I've had the idea of starting up a blog ruminating in my head since a friend shared an [article](https://thejaymo.net/2019/12/14/114-please-for-the-love-of-blarg-start-a-blog/) on his own blog that quotes Warren Ellis as saying:

> I’ve seen the idea circulating for a while: come off the streams, own your own platform for your own voice and your own complete statements. It seems like a reactionary step, from some angles. But maybe that great river, [The Conversation](https://web.archive.org/web/20180128152137/https://arstechnica.com/gaming/2016/05/lavie-tidhars-novel-central-station-is-a-mosaic-of-posthuman-problems/), was, like every river followed to its source, a dead end. The resurgence of the Republic Of Newsletters may be one aspect of a return to the ocean, dotted with little pirate radio stations broadcasting through the night again.

The idea of "owning" my own little place on the internet is super appealing to me, for a couple of reasons: 

1. My biggest use-case for social media was having a snapshot of what I was thinking about / experiencing at a certain point in time. I really used it less as a way to communicate with others directly, and more as a time machine I could browse through to remember what I was up to way back when.
2. I really do enjoy writing, and I think that forcing myself to put things down on a page is part of how I process what I'm thinking through. It helps me synthesize my life into some sembalance of coherence.

So the gist of this little project is to hit on those two goals - to have a snapshot of what I was thinking about, reading, experiencing, listening to, doing, etc. etc. etc., that I can go back to two or three years from now and look back at, and to have a space where I can write whatever I want without getting into the rat race of likes and shares and feeding the voracious and insatiable advertisement-driven monstrosity that is the "walled garden" of modern social media. 

Even if *literally* no-one reads this aside from me, I think it will have served its purpose. But I'm also hoping it can be a sort of pseudo-Facebook for my friends and family too - a space where anyone who is actually interested in my life and what I'm up to can get the big updates. I'd rather not be just part of the volume of some rando scrolling through their feed while they're eating beans or something. 

If you want to get *really* old school, you should be able to subscribe to this blog using RSS to get updates as they come out. No promises on how frequently I'll post here, though. Or even really what the themes or topics will be - I imagine I'll just write about whatever I'm up to. This whole thing is just for fun - I may burn out quickly (but hopefully not!)

Obviously, all of the views expressed here are my own. Duh. They may not be coherent or valuable to anyone but me, but at least they're original!

I'm pulling one last idea from my friend's blog, which is to conclude with some of the things I'm consuming these days. 

### Music
- [Palimpsest - Protest the Hero](https://protestthehero.bandcamp.com/album/palimpsest)
- [Punisher - Phoebe Bridgers](https://phoebebridgers.bandcamp.com/album/punisher)

### Podcasts
- [The Magnus Archives](http://rustyquill.com/the-magnus-archives/)
- [The Besties](https://www.themcelroy.family/besties)
- [You Must Remember This: Six Degrees of Song of the South](http://www.youmustrememberthispodcast.com/episodes/tag/Song+of+the+South)

### Reading
- Bury My Heart at Wounded Knee: An Indian History of the American West - Dee Brown
