---
title: Summer 2021 Wrap-Up
date: 2021-09-06
---

## I hate sand

And just like that, summer is over. It's hard to believe that we're diving headfirst into September already - luckily in Virginia the weather stays pretty nice well into October, so we still have lots of good outdoor time remaining. In my mind, fall is the worst season of the year - mainly because I can't see the colors when the leaves change, and because I hate the cold and not wearing shorts and chapped lips - but I always forget that I end up wearing shorts and t-shirts well into October. So I'm still in the clear for awhile. 

Erin and I just got back from two weeks in the OBX. The first week we were with family in Corolla, and the second week we chilled with friends in Hatteras. Both groups had the same general beach vibe - namely, planning nothing and sitting on the beach drinking White Claws (for me specifically it was Trulys aka the superior White Claw) - so I basically just sat in the same beach chair for two weeks straight, surrounded by sun, surf, and a rotating cast of books. It was fantastic. 

Erin makes fun of me because I only have one swimsuit and thought that could carry me through two full weeks at the beach - but to my credit, I really do think I could have made it on one swimsuit coupled with aggressive use of the washing machine. But to her credit, I did buy some cheap swimsuits at Wings as a backup and ripped one of them right down the middle out in the surf, so she probably was onto something. In the end I was glad I had some fallback trunks. 

I was able to get some good reading done out on those sandy sandy dunes though:

- Our friends started a book club called The Gap Year - its focused on reading books we probably should have read during our educations - so far we've read Plato's *The Republic*, the  *Tao Te Ching*, and *Beowulf*. *Beowulf* is freshest in my mind, having been the most recent book discussion. We read Headley's [feminist translation of the epic poem](https://www.amazon.com/Beowulf-Translation-Maria-Dahvana-Headley/dp/0374110034) which was just published last year. It really is an incredible story. My only previous interaction with *Beowulf* was the kind-of-mostly bad CGI film that came out in 2007, so I didn't really remember much about it. The actual story is really incredible - its such a thoughtful reflection on heroic myth and what is ultimately worth anything when we're faced with our own mortality. The prose of this translation was also just very fun to read - it feels very active, like something that should be spoken aloud. All in all a very enjoyable read. If you've ever been interested in Beowulf but didn't want to deal with a stuffy translation, Headley's translation is quite fun. I've also been thinking alot about how *Beowulf* is an obvious influence on other media I love, like *The Lord of the Rings*, and more recently Michael Crighton's *Eaters of the Dead*. I also caught alot of similarities between *Beowulf* and the video game *Hellblade* which I briefly mentioned in [my last post](https://www.zackverham.com/blog/2021-06-19-hot-corgi-summer/).
- My second book was Joseph Conrad's *Heart of Darkness*. Ehhhhhh. I wasn't super into this one. I know there's a lot of debate around whether the book plays into racist and imperialistic tropes, or if it intentionally inhabits those tropes to  critique them. Even if the book was intentionally playing smart with tropes to dismantle them, I just didn't find the plot or the writing compelling enough to justify giving the novel that much interpretative leniancy. And regardless of the "stance" that you think the novel is taking on imperialism and racial supremacy, its still just an awful, heavy read. I get why the book is considered a classic, but I had a hard time clicking with it. 
- The last book I read took up most of my beach time - Tom Holland's *Dominion* was phenomenal. I had this book on my reading list for quite awhile, and I love having a big, beefy tome at the beach that I can get lost in. The general thesis of Holland's work is that Christianity is so deeply embedded in western thought that it is practially impossible for western society to fully divest itself from Christian thinking and ethics, even as the west continues to become more secularized (small aside - even the delineation between "sacred" and "secular" is a historical inheritance from Christianity, which comes with its own positive and negative baggage). What I loved about this book is that Holland analyzes the history of western Christianity - from St. Paul to the mid 2010s - without the explicitly pro/anti-Christian undertones that you would expect from a book like this. Holland doesn't make his own religious inclinations super explicit, because that's not really the point of the book. The history of Christianity, like the history of the west, is complicated. It doesn't fit into a thesis of "this was uniformly good," or "this was uniformly bad" - rather, the entire package is a messy interlocking development where western Christianity, economics, diplomacy, domestic policy, culture, and a wide selection of other actors all mutually co-inhabit each other and drive mutual mutation or modification (I know 'mutation' is an odd word to place here, but I hesitate to use the word 'development,' because that implies uniform improvement). Holland maintains a grand vision, and the book covers a lot of ground fairly quickly, but I loved getting such a high-level view of western history when its so easy to constrain Christianity to the uniqely American spin-offs which developed in the mid-20th century. 


All in all, two beach weeks made for a great way to wrap up my summer. 

Now onwards into fall!
