---
title: Slice the Cake - Silly Band Name, Great Music
date: 2020-07-03
---

Over the past week (and especially after yesterday's pseudo-live performance for [UK Tech-Fest 2020](https://www.youtube.com/watch?v=ev_pQ8GQvaw), I've become re-obsessed with Slice the Cake's prog-metal magnum opus, *[Odyssey to the West](https://slicethecake.bandcamp.com/album/odyssey-to-the-west)*.  I feel like eventually I'll post something more cohesive about my "Top X Albums," so that my future self can make fun of what I'm currently listening to, but at this point I feel pretty confident that this album would make that list. 

*Odyssey to the West*, which released without much fanfare at least partly because of the complicated [path it took](https://www.metalsucks.net/2016/06/16/odd-yssey-strange-death-slice-cake/) to reach the outside world, deserves at least one listen from front-to-back. The album works *so well* as a cohesive unit. From the spoken word portions that break up the technical masterwork of songs like "Stone and Silver Part II - The Horned God" and the repetition of musical motifs that mutate and change throughout the album (most obviously at the end of the album, in the transition from the swing feel of "Destiny's Fool" into the straight blast beats of "The Holy Mountain"), the album threads within and across itself so that, as a unit, its pretty flawless. 

I have yet to sit down with the lyrics in front of me and piece together the complete narrative that spans the album, but even the bits I have pieced together are beautiful - it is a story akin to Steven King's *The Dark Tower*, a tale of  a quest which tears the protagonist away from his loved ones and throws him into a battle for his own sanity and religious stability, all taking place in some sort of post-apocalyptic hellscape, like if *Mad Max* were a Bildungsroman. 

If you have some time (or if you're like me and want to listen to some brutal shredding while on a long run), I definitely recommend giving this a spin, or just watching their performance Iinked in the video above, which starts at 58:30. 
