---
title: It's Summer!
date: 2023-06-02
---

I'm currently driving back from a week in the OBX with the family - the weather was hilariously bad (we really only got out on the beach for one day), but it was great time with lovely people.

## Reading

- *Ghost Story* by Peter Straub. Very intense and spooky - huge Steven King vibes. 
- *The Great Mortality: An Intimate History of the Black Death, The Most Deastating Plauge of All Time* by John Kelly. A broad historical survey of how different European communities responded to and handled the Black Death. Obviously a bummer, but grotesquely fascinating. 
- *Siddartha* by Hermann Hesse. I don't know a *ton* about this book - its an allegorical novel from the 1920s that engages with Buddhism, but I don't quite know how to put it in any sort of cultural / philosophical context. Its very different from what I'm normally exposed to.

## Playing

- *Subnautica*. Currently trying to survive on an alien water planet.
- *Magic the Gathering: Arena*. Just getting in some practice for paper Magic. 

## Listening

### Podcasts

- *Behind the Bastards*. I finished the series on the Illuminati, and am now deep in the Vince McMahon series. Hilarious so far. 

### Music

- *Take Me Back To Eden* by Sleep Token. Possible AOTY contender already - their best work by a mile.
- *[m]other* by Veil of Maya. *Siddartha* actually references the concept of "Veil of Maya" which is interesting. I think the band pulled their name from the Cynic song, but the original idea seems to come from [Buddhist / Hindu tradition(s)](https://en.wikipedia.org/wiki/Maya_(religion)). Anyways, album shreds.
- *None of the Above* by Structures. Just an absolute monster of an EP.


