---
title: Mar 2021 Book Recommendations
date: 2021-03-02
---

Here’s the promised fast-follow with some additional books that I’ve enjoyed / found interesting. 

## Jesus and John Wayne: How White Evangelicals Corrupted a Faith and Fractured a Nation - Kristen Kobes Du Mez

Phew - this one is a heavy-hitter. I’d say this was probably the most insightful book I read last year. Like most post-evangelical / ex-vangelical / whatever-you-want-to-call-them people who reached a serious point of reckoning with the faith they grew up in after the implosion of white evangelicalism over the past half-decade, I’ve been on the painfully freeing journey of trying to figure out what exactly happened, and why I wasn't aware of what was happening *much* earlier. The 2016 election illuminated for me that white evangelicalism is primarily a political / sociological movement with religious undertones, but I was left with the question: was it *always* like this? Did something fundamentally change over the past few years? Was I just blind and naively unaware of the implications of my denominational alignment? 

Du Mez is able to piece together a compelling account by starting with 2016 and working backward. She argues that the implicit fusing of white evangelicalism with right-wing partisan politics has been baked into the movement through historical processes spanning the past 75 years. Du Mez draws a clear historical line which weaves together Cold War politics, Christian consumerism, and the development of an ethic of virulent masculinity which identifies and explains so many touchpoints from my past and directly explains the current Gordian knot which has locked white evangelicalism in as an incontrovertibly right-wing movement. 

Du Mez was able to answer so many questions I’ve been wrestling with for a long time, and has helped me to identify why I felt so much friction with the tradition of my upbringing that I was forced to walk away from it. 

## Reading While Black: African American Biblical Interpretation as an Exercise in Hope - Esau McCaulley 

Given that the past few years have flipped the entirety of my faith tradition on its head, I’ve been working to not only break apart and examine assumptions that I now think are harmful, but to learn how to rely on hermeneutics from different historical traditions as I’ve been trying to figure out what the radically transformative vision being described by Jesus in the Gospels might actually look like. I know there are just deeper and healthier theological streams than what I grew up with - I’m in the process of learning about those streams and listening to them. 

This book has played a big role in that process. McCaulley’s proposal is to develop and analyze a framework for Biblical exegesis which relies on the historical readings that have come directly from lived experience within the Black church. He sees this as a “third way” which is an alternative to pure academia (which tends to read Scripture with a well-developed eye for literary and historical criticism, but minimizes the concrete transformative power of the Gospel as it exists within lived individual experience) and religious fundamentalism (which has a strong emphasis on the way that the Bible works on the human soul, but fails to take the text itself seriously through its naive reliance on inerrancy as an interpretative crutch). 

I really loved this book. I don’t think I’m in a position to offer much in the way of analysis of the content of the book, because it is drawing from and speaking to a history and a theology which I have not and will not experience directly. But even as an outsider peering into the world that McCaulley is describing, I think what he has laid out in this book is quite beautiful and offers a robust response for what in the world I’m supposed to do with the Bible now. 

## The Once and Future King - T.H. White
Given how much I love fantasy, its a bit surprising that I’m not very familiar with the Arthurian myths. This was my first serious foray into Arthur, and from what I can tell this is one of the strongest / most beloved iterations of the Arthurian myth. *The Once and Future King* is split into four books which cover different phases of Arthur’s life (fun fact: the first book is the source for the Disney’s *The Sword in the Stone*). 

White takes some creative license with the mythology in order to merge the Arthurian tales with commentary on the world as it existed immediately after both world wars. Arthur spends a lot of time thinking through and analyzing ways to minimize suffering and the role that war (or general application of force) plays in the creation of peace.

My favorite portion of *The Once and Future King* was *Book III - The Ill-Made Knight*, which focuses on the life of Sir Lancelot and his tragic romance with Queen Guenever. Lancelot is just so well written - complex and messy and inconsistent, but in ways that were paradoxically true to himself and his ideals. This was definitely a fun read - and now the board game *Avalon* makes so much more sense!
