---
title: Feb 2021 Book Recommendations
date: 2021-02-27
---

I suppose the last time I put up a list of recommended books was last summer, so this doesn’t really fit as a specific interval-of-time update. But given that it’s been awhile, I figured I’d track some good reads from both the second half of last year, and the chilly, wintry beginning of this one. 

## Ring Shout - P. Djèlí Clark
This was *such* a cool novella. I've loved seeing the recent development of Lovecraftian horror which directly confronts the white supremacist notions that were baked into the mythos by its titular author. I haven’t read *Lovecraft Country* yet, but I know it works towards a similar inversion of tropes. 

I don’t want to spoil much about this book - you should just go into it blind, its a short read and its really well written. All I’ll say is that it mixes the concrete cultural horrors of southern white supremacy in the early-to-mid 1900s with cosmic horror in really original and insightful ways. Really, really cool read. 

## The Devil in America - Kai Ashante Wilson 
This one’s a short story which also mixes reflection on the horrors of southern racial prejudice with horror as a literary genre. I can give the cop-out of saying that I can’t really talk about this one without spoiling it, but honestly I’m moreso just at a loss for words. I don’t think I can give a teaser for this story without corrupting what it is doing in some way. 

The ending is absolutely horrific though - not an easy read, by any means. Just a warning in case you decide to check it out - it is a stunning work, but it is very dark. 

## Revelations of Divine Love - Julian of Norwich
I honestly don’t know much about the Christian mystics - I wish I did. My religious upbringing focused on Scripture as the sole source of divine revelation. The obvious potential weakness with this approach is that the Bible is a known quantity. There’s no hidden information - you have the entirety of the Bible in front of you, whenever you want it, which gives the impression that God is a “knowable” quantity that can be leveraged and manipulated and forced into whatever box you want to force God into. 

Julian was a 14th century Christian mystic who claimed to have received a series of mystical visions during an illness which nearly killed her. She herself didn’t know exactly what to do with the visions, and spent 20 years reflecting on them - these reflections are collected into the “longer” of two manuscripts which are the original sources for the text. The visions are weird and messy in beautiful ways. Take this quote, for example: 

> “Jesus is our very Mother, not feeding us with milk, but with himself; opening his side to us, and challenging all our love. ”

Or this one: 

> “For in our Mother Christ we profit and increase, and in Mercy he reformeth us and restoreth, and, by the virtue of his Passion and Death and Uprising, oneth us to our Substance. This worketh our Mother in Mercy to all his children which are to him buxom and obedient.”

In her visions, Julian is not interacting with a known quantity. She is interacting with something unknowable, something that cannot be leveraged into a clean meditative reflection on the Divine. She had to spend most of her life working out what these visions meant, and even in the final manuscript, she records herself doubting whether she made everything up, in the end. 

This book was a really beautiful and honest account of something incomprehensible, which is a balm for the arrogance and overconfidence that often appears in modern religious discourse. 

## Lord of the Flies - William Golding
Yes, I should have read this in middle or high school like literally everyone else in America did, but for whatever reason, I didn’t. I remember my classmates talking about this book when they read it, but the discussions were always lighthearted and silly in the ways that children’s conversations inevitably have to be. I’m sort of glad I read this as an adult - I think a lot of the apocalyptic and dystopian implications that Golding is laying out here really only make sense and are contextualized when I’m a “real human man” (tm) who, somehow, has to play the tiniest of roles in making sure that society doesn’t fall apart. It feels like the fragility of the world was uniquely on display in 2020 - what Golding was trying to say with this book really feels especially apt as we, as both a nation and a species, are in many ways just trying to make sense of what the hell actually happened last year, across many, many dimensions of our messy and embodied sociopolitical lives. 

Also, Simon is the best character in the book, hands down. 

## Discipline and Punish: The Birth of the Prison - Michel Foucault

A very dense (but helpful) book. Foucault begins by observing that western society made a really rapid transition from corporal punishment / public executions to imprisonment as the primary form of judicial punishment. Like, *really* rapid. Which, of course, begs the question - what factors drove this dramatic shift in penal justice? Foucault pushes against the notion that charitable reform was the primary driver of this change, and instead proposes that the development of *discipline* as a social norm and its relationship to industrial capitalism drove the creation of a form of punishment which emphasized the observation and rehabilitation of criminality, adjusting it towards social norms with the ultimate goal being the reforming of the productivity of convicts. This was a shift from the form of penal justice which sought direct restitution for harms committed, directly or indirectly, against the absolute (and inconsistently applied) power of a monarchy, which was historically expressed through torture and public execution. 

Obviously, there’s too much going on here to unpack in any meaningful way, but this book did help to contextualize a few specific things for me. For example, Foucau lt comments on some issues that feel very current, like: 

- The moral atrocities inherent in the development of “felon” as an extra-judicial social class
- The consistency of “prison reform” as a stated goal which never actually gets anything done

I’m very glad I read this - definitely makes me want to dig into more of Foucault. 



*I have some other books I’d like to add to this post, but its already getting kind of long - maybe I’ll follow up shortly with a part 2.* 
