---
title: Happy May!
date: 2021-05-01
---

Well friends, we made it to May! I don't have a cohesive post here - but I was thinking about how different my world feels this May than it did a year ago. Last year I was scared to see my family on my birthday and was trying to figure out if it was safe to sit with friends in an open field. This year, I'm kicking off my first week post-second-dose-of-moderna (which, by the way, absolutely destroyed me), and I'm already thinking about what it might look like for concert venues and movie theaters to be safe again. I'm looking forward to a summer that could potentially begin to have some semblance of normalcy, rather than the endless humid, sweaty abyss that stretched out before me last year. It feels like 2021 is actually here now, and I'm so thankful. 

Some stuff I'm currently into: 

- The BBC has been [reimagining H.P. Lovecraft's horror stories](https://www.bbc.co.uk/programmes/p06spb8w) as investigative crime podcasts set in modern times. I binge listened to all three seasons in like a week. It was actually *really* helpful in contextualizing some of the larger canon of the Cthulhu Mythos - hearing some of the stuff about the Outer Gods and such explained in modern vernacular made a lot more sense than trying to figure out what Lovecraft was even trying to describe in some of his stories. Obviously the podcast takes some liberties with the source material to make it work as a podcast, but still - really cool, would recommend. It seems like the BBC has a bunch of weird horror podcasts that I'm planning on checking out. 
- Hail the Sun's new release, [New Age Filth](https://hailthesun.bandcamp.com/album/new-age-filth), shreds. "Solipsism" is probably my favorite song on the album right now, but its a really tight record - there's no real cruft or filler here. 
- I'm about 3/4 of the way through Beth Allison Barr's book [The Making of Biblical Womanhood: How the Subjugation of Women Became Gospel Truth](https://www.goodreads.com/book/show/54233271-the-making-of-biblical-womanhood), and I can already tell it'll probably be one of my top books of the year. I won't try to give a full summary here (since I haven't finished it), but I wanted to at least point out a couple of highlights so far. Dr. Barr is a medieval scholar who argues that the development of the "Biblical Womanhood" movement, and the modern emphasis on complementarianism / patriarchy in certain evangelical circles, is largely a descendant of the social and cultural (read: patriarchical) pressures which existed in the larger social fabric of Europe during the Reformation. She proposes that both the exegesis and translation of Reformation-era English scriptures were influenced by a need to justify patriarchy, and that you see a markedly different relationship to Scripture if you back up past the Reformation and look at medieval Christians. Absolutely wild - and she brought receipts! She very clearly is an expert on what she writes about. I love the academic side of the book, but its also a deeply personal text - Barr contextualizes alot of the meatier segments with her experiences in the Baptist church, which I directly relate to and understand - it brings up lots of memories (and, honestly, some sadness). Really really cool book - I'm basically underlining the entire thing. 
- Speaking of medieval Europe, I'm really enjoying my time with [Crusader Kings 3](https://www.youtube.com/watch?v=bs0zhMCul5Q). I'm currently trying to unite Ireland, but my son and primary heir just died of consumption, so I'm not sure if my dynasty will survive another generation. 
