---
title: Some Reflections on Creativity, Faith, and Burnout During Covid-Times 
date: 2020-10-25
---

Its become the single unifying cliche of 2020 to talk about the collapse of all of the creative ways we planned to make use of the global pandemic-induced staycation. Everyone started their bunkering-down with lofty dreams of writing, reading, composing, painting, programming, getting fitter, eating healthier, sleeping better, praying better, etc etc etc. And none of us have actually done any of that. The best I can do is throw out a blog post about how unproductive I am and call it a day. 

If I’m honest, I definitely feel cognitive dissonance and the anxiety around how I’ve used the past 8ish months. I have the desire to spend the pandemic being fruitful and productive. I make all of these plans and todo lists and programming and writing projects for myself, and then I feel like garbage when, a week later, I’ve only taken a half-assed stab at getting anything done. Even if I do get my arbitrary projects done, I then find myself critiquing what I did as a total waste of time, as something that isn’t valuable (or isn’t going to generate value by some ridiculous and arbitrary metric I subconsciously make up on the spot). Part of that anxiety seems to be universal. Part of what I’m feeling also seems  [unique to the sociological and psychological lens through which millennials interact with the world](https://www.buzzfeednews.com/article/annehelenpetersen/millennials-burnout-generation-debt-work). 

I could stand on the soapbox provided to me by my evangelical upbringing and talk about how my worth isn’t tied up in my productivity or my generated value, but that our worth is measured in terms of the presence of the *imago dei* which marks every human soul. But I don’t think saying those things really makes people feel less anxious. I also don’t think white American evangelicalism is really in an especially good place to be trying to critique a system [it is inherently tied up in](https://kristindumez.com/books/jesus-and-john-wayne/) and helped create, but that is a different discussion altogether. Those ideas certainly doesn’t make me feel less anxious, but I don’t really know whether that’s because I don’t trust the sentiment, or because I don’t trust the system that told me the sentiment anymore.

I think that my experience as a practicing Christian *should* have something to say in response to my feelings of (perhaps capitalistic and consumption-driven) inadequacy and failure during the pandemic. If I’m honest, I don’t know exactly what that response is without delving into more Christian cliches that don’t actually make me feel like less of a jackass. I also honestly hate the idea of a nice, beautiful bow that can wrap up the morality and ethics of non-productivity and non-creativity during the pandemic when people are facing the more dire crises of serious illness, suffering, and disease. 

All that to say, I feel just as lost and confused during the pandemic as everyone else, and maybe it’s ok to just acknowledge that none of us really know what we’re doing or how to cope with anything. The solutions may come later, but for me, it’s a relief to just say that I have no clue what I’m doing with my time these days. At all. 
